# Generated by Django 5.1.4 on 2025-03-08 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bikemodification",
            name="bike_model",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bike_model",
                to="catalog.bikemodel",
            ),
        ),
    ]
